#!/usr/bin/env python3
import json 
from pprint import pprint
with open('1234567.json') as data_file:    
    data = json.load(data_file)

pprint(data)
print("student name: " + data["student-name"])
print("home phone: " + data["home-phone"])
print("parents/guardian: " + data["guardians"])
